# -*- coding: utf-8 -*-
"""EPSRC_preprocessing_final_tocomment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1QSgvw5l6x4LGWH0E4Wm_0ESwyqLWjE
"""

'''
Preprocessing and train/test split for the Kruger camera-trap dataset (2015-2016).

This script prepares labelled image lists for training an image classifier on camera_trap species data.

Outputs (written to ./output/):
  train_labels.csv, test_labels.csv: image lists with labels and file paths
  label_map.json: species name -> integer class ID
  test_pool_raw.csv, train_pool_raw.csv: fixed test set and pool of images available for training
  multi_species_summary.csv, multi_species_exclude_list.csv: images excluded for having more than one species/ annotation row
'''

import pandas as pd
import numpy as np
from pathlib import Path
import json

# --- Configuration ---

# Paths to data annotations csv and image folders for each year
# Update these to match where the data lives on your machine
DATA_DIR = Path(__file__).resolve().parent / "data"

input_csv = DATA_DIR / "Kruger_2015_16_annotations_dupes_removed_final4.csv"
image_root_2015 = DATA_DIR / "2015"
image_root_2016 = DATA_DIR / "2016"

# Data filtering/splitting parameters
threshold = 300                # keep only species with at least this many images in total
split_year = 2016              # images from this year onwards are treated as "2016"
test_proportion = 0.25         # fraction of each species' images (per year) reserved for testing
min_test_images_per_year = 30  # minimum test images per species per year
random_state = 0               # random seed for reproducible sampling

# Experiments: number of training images per species drawn from 2015 and 2016
EXPERIMENTS = {
  "2015_only": (600, 0),    # train on 2015 data only
  "1_1":       (300, 300),  # equal mix of 2015 and 2016
  "5_1":       (500, 100)   # 5:1 ratio of 2015 to 2016
}
EXPERIMENT_NAME = "5_1"     # which experiment to build
train_images_2015, train_images_2016 = EXPERIMENTS[EXPERIMENT_NAME]

# Set to True to discard the saved test set and rebuild it from scratch
#Leave False so every experiment is evaluated on the same test images
FORCE_REBUILD_TEST_SET = False

print(f"Experiment: {EXPERIMENT_NAME},    seed: {random_state}")

# Columns that together identify a single image
image_key = ["site", "camera", "folder", "filename"]

# Create output folder inside directory (if it does not exist) and write results to there
output_dir = Path("output")
output_dir.mkdir(parents=True, exist_ok=True)

# --- Helper functions ---

def build_path(row):
  '''
  Takes a row of the annotation dataframe and builds file path to that image.

  Images stored as:
    <year root>/<site>/<date_range>/<camera>/<folder>/<filename>
  '''
  root = image_root_2015 if row["year"] == 2015 else image_root_2016  # determine which year, and therefore image root, to use
  return str(root / row["site"] / row["date_range"] / row["camera"] / str(row["folder"]) / row["filename"])

def allocate_quota(site_counts, n_total):
  '''
  Split `n_total` images as evenly as possible across the sites in site_counts capped by amount each site actually has.
  Leftover quota from sites that run out gets redistributed to sites that still have images.

  Inputs:
    site_counts: pd.Series mapping site name to number of images available
    n_total: total number of images to allocate

  Returns:
    dict mapping site name to number of images to take from that site
  '''
  allocation = {site: 0 for site in site_counts.index}    # initiate allocation for all sites to be 0
  remaining_quota = min(n_total, int(site_counts.sum()))  # cap quota- cannot allocate more than exists
  active_sites = set(site_counts.index)                   # track which sites can still give images

  while remaining_quota > 0 and active_sites:
    share = max(1, remaining_quota // len(active_sites))  # calculate even share for each site (at least 1)
    for site in list(active_sites):
      if remaining_quota <= 0:                            # stop if quota runs out part way through
        break
      available = site_counts[site] - allocation[site]    # images this site has not yet given
      if available <= 0:                                  # remove site if already exhausted
        active_sites.discard(site)
        continue

      # Take the smallest of: this rounds target share,
      # what it can actaully give, and what quota remains globally
      take = min(share, available, remaining_quota)
      allocation[site] += take                            # record the allocation
      remaining_quota -= take                             # subract the allocation from the global remaining pool
      if allocation[site] >= site_counts[site]:           # if site has hit its cap, drop it
        active_sites.discard(site)

  return allocation                                       # return allocation for each site

def duplicate_to_quota(pool, n_needed, random_state):
  '''
  Choose `n_needed` rows from `pool` to duplicate, spread evenly across sites.

  Used when a species does not have enough unique training images to reach its target. If `n_needed` is larger than `pool`, duplication is
  done in successive passes over the whole pool.

  Inputs:
    pool: DataFrame of images already selected for training
    n_needed: number of extra (duplicate) rows needed
    random_state: random seed

  Returns:
    DataFrame of `n_needed` rows drawn from `pool` (fewer only if `pool` is empty)
  '''
  dup_parts = []
  remaining_needed = n_needed
  pass_num = 0

  while remaining_needed > 0:
    pass_num += 1
    this_pass_n = min(remaining_needed, len(pool))  # at most one copy of each image per pass

    # Decide how many duplicates to take from each site in this pass
    site_counts = pool["site"].value_counts()
    allocation = allocate_quota(site_counts, this_pass_n)

    pass_parts = []
    for site, n in allocation.items():
      if n <= 0:
        continue
      site_rows = pool[pool["site"] == site]

      # Different random_state per pass so later passes don't repeat earlier picks
      pass_parts.append(site_rows.sample(n=n, random_state=random_state + pass_num))
    pass_df = pd.concat(pass_parts) if pass_parts else pool.iloc[0:0].copy()

    dup_parts.append(pass_df)
    remaining_needed -= len(pass_df)

    if len(pass_df) == 0:
      break   # nothing left to duplicate from, avoid an infinite loop

  return pd.concat(dup_parts) if dup_parts else pool.iloc[0:0].copy()

def sample_balanced(group, n_total, random_state):
  '''
  Draw up to `n_total` images from `group`, spread across sites via allocate_quota().

  Inputs:
    group: DataFrame of images for one species in one year
    n_total: number of images to draw
    random_state: random seed

  Returns:
    (sampled, remaining): the drawn images and everything left over
    If `group` has `n_total` images or fewer, all of them are returned as `sampled` and remaining is empty
  '''
  site_counts = group["site"].value_counts()  # images available per site
  total_available = len(group)

  # Not enough images to be selective, take everything
  if total_available <= n_total:
    return group.copy(), group.iloc[0:0].copy()

  # Decide how many images to take from each site
  allocation = allocate_quota(site_counts, n_total)

  # Randomly sample the allocated number of images from each site
  sampled_parts = []
  for site, n in allocation.items():
    if n <= 0:
      continue
    site_rows = group[group["site"] == site]
    sampled_parts.append(site_rows.sample(n=n, random_state=random_state))

  sampled = pd.concat(sampled_parts) if sampled_parts else group.iloc[0:0].copy()
  remaining = group.drop(sampled.index)  # everything not sampled
  return sampled, remaining

def build_year_train(remaining_pool, target, random_state, binomial, year_label):
  '''
  Build the training images for one species from one year.

  Draws up to `target` images from `remaining_pool` (site-balanced). If the pool has fewer than `target` images, existing
  images from that same pool are duplicated to make up the difference. Duplicated rows are flagged with `is_duplicate = True`.

  Inputs:
    remaining_pool: images for this species/year not reserved for testing
    target: number of training images wanted
    random_state: random seed
    binomial: species name
    year_label: year as a string

  Returns:
    (train_subset, leftover_subset): the training images (including any duplicates) and any pool images not used for training
  '''
  tr_year, rem_year = sample_balanced(remaining_pool, target, random_state)
  tr_year = tr_year.copy()
  tr_year["is_duplicate"] = False

  if len(tr_year) < target and len(tr_year) > 0:
    # Too few unique images- top up with duplicates
    duplicate_needed = target - len(tr_year)
    unique_available = len(tr_year)
    print(f"  Note: {binomial} has {unique_available} usable {year_label} training images (after reserving test) "
          f"duplicating to add {duplicate_needed} more and reach {target}"
          + (f" (some images will appear more than twice)" if duplicate_needed > unique_available else ""))

    duplicated_rows = duplicate_to_quota(tr_year, duplicate_needed, random_state).copy()
    duplicated_rows["is_duplicate"] = True
    tr_year = pd.concat([tr_year, duplicated_rows])

  elif len(tr_year) == 0 and target > 0:
    print(f"  Warning: {binomial} has no {year_label} images left for training after reserving test set")

  return tr_year, rem_year

# --- Main pipeline ---

def main():
  '''
  Main preprocessing function. Handles data cleaning and train/test allocation.
  '''
  # --- Load and clean annotations ---

  # Drop any remaining exact duplicates
  df = pd.read_csv(input_csv)
  print(f"Number of rows: {len(df)}")
  df = df.drop_duplicates().reset_index(drop=True)
  print(f"After duplicate removal: {len(df)}")

  # Drop 'unknown'/'rare' binomials, and Nwaswitshaka site (2015)
  df = df[(df["binomial"] != "unknown") &
          (df["binomial"] != "rare") &
          (df["site"] != "Nwaswitshaka")].reset_index(drop=True)
  print(f"After dropping 'unknown'/'rare' binomials and Nwaswitshaka: {len(df)}")

  # Label used to count distinct species per images
  # binomial where present, otherwise the common species name
  df["label_for_grouping"] = df["binomial"].fillna(df["species"])

  # Checks for inconsistencies in data set, eg. missed duplicates, singular mistakes, etc.
  # If all ok, should just print 'True'
  ts_per_group = df.groupby(image_key)["timestamp"].nunique()
  assert (ts_per_group == 1).all(), "Found an image group with inconsistent timestamps"
  dr_per_group = df.groupby(image_key)["date_range"].nunique()
  print(f"Each image has a single date_range: {(dr_per_group == 1).all()}")

  # --- Collapse to one row per image and keep single-species images only ---

  summary = (df.groupby(image_key).agg(
      n_lines = ("label_for_grouping", "size"),                       # annotation rows for this image
      n_species = ("label_for_grouping", "nunique"),                  # distinct species in this image
      binomial = ("binomial", "first"),                               # image label (first row's binomial)
      species_list = ("species", lambda s: sorted(set(s.dropna()))),  # species name list, for readability
      timestamp = ("timestamp", "first"),                             # timestamp for image
      date_range = ("date_range", "first")                            # date range for image
  ).reset_index())

  def classify(row):
    '''
    Classify each image as single-species, multi-species, or a repeated single species.
    '''
    if row["n_lines"] == 1:
      return "single_species"
    elif row["n_species"] > 1:
      return "multi_species"
    else:
      return "multi_line_same_species"  # same species logged twice

  summary["category"] = summary.apply(classify, axis=1)
  print("\nImage-level breakdown: ")
  print(summary["category"].value_counts())

  # Save details of excluded multi-row images for reference
  excluded_multi = summary[summary["category"].isin(["multi_species", "multi_line_same_species"])].copy()
  excluded_multi["species_list"] = excluded_multi["species_list"].apply(lambda x: ";".join(x))
  excluded_multi.to_csv(output_dir / "multi_species_summary.csv", index=False)
  excluded_multi[image_key + ["category"]].to_csv(output_dir / "multi_species_exclude_list.csv", index=False)

  # Keep single-species images that actually have a species label
  # (images with 'NA' binomial are empty frames)
  clean = summary[summary["category"] == "single_species"].copy()
  n_empty = clean["binomial"].isna().sum()
  clean = clean[clean["binomial"].notna()].copy()
  print(f"\nDropped {n_empty} empty images (single line, no binomial)")
  print(f"Clean single-species, labeled images: {len(clean)}")

  # --- Add year and day/night columns ---

  timestamps = pd.to_datetime(clean["timestamp"])
  clean["year"] = timestamps.dt.year

  # Daytime is between average sunsrise (06:22) and average sunset (17:26)
  sunrise_hour = 6 + 22/60
  sunset_hour = 17 + 26/60
  decimal_hour = timestamps.dt.hour + timestamps.dt.minute/60 + timestamps.dt.second/3600
  clean["day_night"] = np.where((decimal_hour >= sunrise_hour) & (decimal_hour < sunset_hour), "day", "night")

  # --- Keep only species with enough images ---

  species_year_counts = clean.groupby(["binomial", "year"]).size().unstack(fill_value=0)  # images per (species, year)
  count = species_year_counts.sum(axis=1)                                                 # total per species
  keep_species = count[count >= threshold].index.tolist()
  print(f"\nSpecies with >= {threshold} images ({len(keep_species)} kept), by year: ")
  print(species_year_counts.loc[keep_species].sort_values(by=list(species_year_counts.columns), ascending=False))

  dropped_species = count[count < threshold]
  print(f"\nDropped {len(dropped_species)} species below threshold, {dropped_species.sum()} images")

  clean = clean[clean["binomial"].isin(keep_species)].copy()

  print("\nDay/night breakdown, by species: ")
  print(clean.groupby(["binomial", "day_night"]).size().unstack(fill_value=0))

  # --- Fixed test set ---

  # Only the first run (for whichever experiment you happen to build first) decides the test set
  # every run after that just loads it unchanged. Set FORCE_REBUILD_TEST_SET = True to rebuild.

  test_pool_path = output_dir / "test_pool_raw.csv"
  train_pool_path = output_dir / "train_pool_raw.csv"

  if test_pool_path.exists() and train_pool_path.exists() and not FORCE_REBUILD_TEST_SET:
    print(f"\nFixed test/train pool already exists- reusing it unchanged "
          f"(delete {test_pool_path.name}/{train_pool_path.name} to rebuild from scratch)")
    test_df = pd.read_csv(test_pool_path)
    train_pool_df = pd.read_csv(train_pool_path)
  else:
    print("\nNo fixed test/train pool found- building it now (this only happens once)")
    test_parts, pool_parts = [], []

    for binomial, group in clean.groupby("binomial"):
      # Split this species' images by year
      group_2015 = group[group["year"] < split_year]
      group_2016 = group[group["year"] >= split_year]
      n_2015 = len(group_2015)
      n_2016 = len(group_2016)

      # Test size per year: test_proportion of the images, but at least min_test_images_per_year
      test_target_2015 = max(round(n_2015 * test_proportion), min_test_images_per_year)
      test_target_2016 = max(round(n_2016 * test_proportion), min_test_images_per_year)

      # Site-balanced test sample per year, rest becomes the training pool
      te_2015, pool_2015 = sample_balanced(group_2015, test_target_2015, random_state)
      te_2016, pool_2016 = sample_balanced(group_2016, test_target_2016, random_state)

      print(f"  {binomial}: test_2015 = {len(te_2015)} (target {test_target_2015}, had {n_2015}), "
            f"test_2016 = {len(te_2016)} (target {test_target_2016}, had {n_2016})")

      test_parts.append(te_2015)
      test_parts.append(te_2016)
      pool_parts.append(pool_2015)
      pool_parts.append(pool_2016)

    test_df = pd.concat(test_parts).reset_index(drop=True)
    train_pool_df = pd.concat(pool_parts).reset_index(drop=True)

    # Save the fixed split so later runs can reuse it
    pool_cols = image_key + ["binomial", "year", "day_night", "date_range"]
    test_df[pool_cols].to_csv(test_pool_path, index=False)
    train_pool_df[pool_cols].to_csv(train_pool_path, index=False)
    print(f"Saved fixed test/train pool to {test_pool_path.name}/{train_pool_path.name}")

  # --- Build training set for this experiment ---

  # Draws train_images_2015 and train_images_2016 images per species from the training pool.
  # Pool images not selected are simply unused (ie. not added to test set).

  print(f"\nBuilding train set for experiment"
        f"(2015 target = {train_images_2015}, 2016 target = {train_images_2016})")
  train_parts = []
  for binomial, group in train_pool_df.groupby("binomial"):
    group_2015 = group[group["year"] < split_year]
    group_2016 = group[group["year"] >= split_year]

    tr_2015, _ = build_year_train(group_2015, train_images_2015, random_state, binomial, "2015")
    tr_2016, _ = build_year_train(group_2016, train_images_2016, random_state, binomial, "2016")

    train_parts.append(pd.concat([tr_2015, tr_2016]))

  train_df = pd.concat(train_parts).reset_index(drop=True)
  test_df = test_df.copy()
  test_df["is_duplicate"] = False  # test images are never duplicated

  # Summeries of the final split
  print(f"\nTrain images: {len(train_df)}")
  print(f"Test images: {len(test_df)} (identical across every experiment)")
  print(f"\nTrain per (binomial, year): ")
  print(train_df.groupby(["binomial", "year"]).size().unstack(fill_value=0))
  print(f"\nTest per (binomial, year): ")
  print(test_df.groupby(["binomial", "year"]).size().unstack(fill_value=0))
  print(f"\nTest per (binomial, day/night): ")
  print(test_df.groupby(["binomial", "day_night"]).size().unstack(fill_value=0))

  # How much each species relied on duplication to reach its target
  print("\nDuplication summary per binomial (0 duplicate_rows = quota met without duplication): ")
  dup_summary = train_df.groupby("binomial").apply(
      lambda d: pd.Series({
          "duplicate_rows": int(d["is_duplicate"].sum()),
          "unique_images": len(d.drop_duplicates(subset=image_key)),
          "max_copies_of_one_image": int(d.groupby(image_key).size().max()),
      }),
      include_groups=False,
  )
  print(dup_summary)

  # --- Leakage check and output files ---

  # No image should appear in both train and test (should print 0)
  train_images_set = set(map(tuple, train_df[image_key].values))
  test_images_set = set(map(tuple, test_df[image_key].values))
  overlap = train_images_set & test_images_set
  print(f"\nTrain/test leakage check: {len(overlap)} overlapping images")

  # Map each species name to an integer class ID (alphabetical order)
  label_map = {sp: i for i, sp in enumerate(sorted(keep_species))}
  with open(output_dir / "label_map.json", "w") as f:
    json.dump(label_map, f, indent=2)

  # Write train_labels.csv and test_labels.csv
  for name, split_df in [("train", train_df), ("test", test_df)]:
    split_df = split_df.copy()
    split_df["label_id"] = split_df["binomial"].map(label_map)                 # integer class label
    split_df["day_night_id"] = (split_df["day_night"] == "day").astype(int)    # day/night ID column (1 = day, 0 = night)
    split_df["filepath"] = split_df.apply(build_path, axis=1)                  # full filepath to the image

    out_cols = image_key + ["binomial", "label_id", "year", "day_night", "day_night_id", "is_duplicate", "filepath"]
    split_df[out_cols].to_csv(output_dir / f"{name}_labels.csv", index=False)

  print(f"\nWrote label files and label_map.json to {output_dir}/")

if __name__ == "__main__":
  main()