# -*- coding: utf-8 -*-
"""EPSRC_training_final_tocomment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjVRlF0xMIO0DJUIeacv0Cp3EXh6lvlj
"""

'''
Train and evaluate a ResNet-18 species classifier on Kruger camera-trap images.

This script reads the label files produced by `preprocess.py`.

Inputs (from preprocess.py, in ./output/):
  train_labels.csv, test_labels.csv
  label_map.json

Output:
  resnet18_species.pt: best model weights plus the label map
'''

import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms
from sklearn.metrics import confusion_matrix, classification_report

from pathlib import Path
from PIL import Image
import json
import random
import numpy as np

# --- Configuration ---

# Input files written by preprocess.py
data_dir = Path("output")
train_csv = data_dir / "train_labels.csv"
test_csv = data_dir / "test_labels.csv"
label_map_json = data_dir / "label_map.json"

# Training hyperparameters
batch_size = 32
num_epochs = 7
learning_rate = 1e-5
feature_extract_only = False  # True: frozen feature extraction (final layer only), False: fine tuning
num_workers = 4
checkpoint_path = Path("resnet18_species.pt")

# Every image has a 100 pixel timestamp strip along the bottom
# Cropped off to avoid bias
crop_bottom_px = 100

seed = 0  # random seed for reproducibility

# Use the GPU if one is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- Reproducibility ---

def set_seed(seed: int):
  '''
  Seed every RNG used by the pipeline
  '''
  torch.manual_seed(seed)  # PyTorch RNG (CPU and CUDA)
  random.seed(seed)        # Python's random module
  np.random.seed(seed)     # NumPy's global RNG

  # Stop cuDNN benchmarking different convolution algorithms (choice can vary between runs)
  # Force deterministic implementations
  torch.backends.cudnn.benchmark = False
  torch.backends.cudnn.deterministic = True

def seed_worker(worker_id):
  '''
  Seed NumPy and Python's random module inside each DataLoader worker process, so data loading
  is reproducible when num_workers > 0.

  Adapted from the PyTorch reproducibility documentation:
  https://pytorch.org/docs/stable/notes/randomness.html
  '''
  worker_seed = torch.initial_seed() % 2**32
  np.random.seed(worker_seed)
  random.seed(worker_seed)

# --- Dataset and transforms ---

class CameraTrapDataset(Dataset):
  '''
  Camera-trap images listed in a label CSV from preprocess.py.

  Each item is returned as (image, label_id, year, day_night_id), where day_night_id
  is 1 for day and 0 for night. Year and day/night are not used for training- they are
  returned so accuracy can be broken down by them.
  '''
  def __init__(self, csv_path, transform=None):
    self.df = pd.read_csv(csv_path)
    self.transform = transform

  def __len__(self):
    return len(self.df)

  def __getitem__(self, idx):
    row = self.df.iloc[idx]
    image = Image.open(row["filepath"]).convert("RGB")

    # Crop off timestamp strip at bottom of every image
    width, height = image.size
    image = image.crop((0, 0, width, height - crop_bottom_px))

    if self.transform:
      image = self.transform(image)

    label = int(row["label_id"])
    year = int(row["year"])
    day_night = int(row["day_night_id"])
    return image, label, year, day_night

# Standard ImageNet normalisation (matches pretrained weights)
imagenet_mean = [0.485, 0.456, 0.406]
imagenet_std = [0.229, 0.224, 0.225]

# Training: random augmentation so the model sees varied versions of each image
train_transform = transforms.Compose([transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),  # random crop covering 80-100% of image
                                      transforms.RandomHorizontalFlip(),
                                      transforms.RandomRotation(degrees=15),
                                      transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
                                      transforms.ToTensor(),
                                      transforms.Normalize(imagenet_mean, imagenet_std)])

# Testing: fixed resize and centre crop, no randomness
test_transform = transforms.Compose([transforms.Resize(256),
                                     transforms.CenterCrop(224),
                                     transforms.ToTensor(),
                                     transforms.Normalize(imagenet_mean, imagenet_std)])

# --- Model ---

def build_model(num_classes: int) -> nn.Module:
  '''
  Load an ImageNet-pretrained ResNet-18 and replace its final layer with a new one that
  outputs `num_classes` scores.

  If `feature_extract_only` is True, all pretrained layers are frozen, so only the new final
  layer is trained.
  '''
  model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

  if feature_extract_only:
    for param in model.parameters():
      param.requires_grad = False

  # Replace final fully connected layer
  in_features = model.fc.in_features
  model.fc = nn.Linear(in_features, num_classes)

  return model.to(device)

# --- Training/evaluation loops ---

def run_epoch(model, loader, criterion, num_classes, optimizer=None):
  '''
  Run one pass over `loader`.

  If `optimizer` is given, the model is trained, otherwise it is only evaluated (no gradients or weight updates).

  Returns:
    epoch_loss: mean loss over all images
    epoch_acc: overall accuracy
    per_class_acc: list of accuracy per class
    per_year_acc: {year: accuracy}
    per_class_year_acc: {class: {year: accuracy or None}}
    per_period_acc: {day_night_id: accuracy}
    per_class_period_acc: {class: {day_night_id: accuracy or None}}

  `None` means that class had no images in that year/period.
  '''
  is_train = optimizer is not None
  model.train() if is_train else model.eval()

  # Running totals across all batches
  total_loss, total_correct, total_seen = 0.0, 0, 0
  class_correct = torch.zeros(num_classes)  # correct predictions per class
  class_total = torch.zeros(num_classes)    # image count per class
  year_correct = {}                         # correct predictions per year
  year_total = {}                           # image count per year
  class_year_correct = {}                   # correct predictions per (class, year) pair
  class_year_total = {}                     # image count per (class, year) pair
  period_correct = {}                       # correct predictions per day/night
  period_total = {}                         # image count per day/night
  class_period_correct = {}                 # correct predictions per (class, day/night) pair
  class_period_total = {}                   # image count per (class, day/night) pair

  # Only track gradients when training
  with torch.set_grad_enabled(is_train):
    for images, labels, years, periods in loader:
      images, labels, years, periods = (images.to(device, non_blocking=True),
                                        labels.to(device, non_blocking=True),
                                        years.to(device, non_blocking=True),
                                        periods.to(device, non_blocking=True))

      # Forward pass
      outputs = model(images)
      loss = criterion(outputs, labels)

      # Backward pass and weight update (training only)
      if is_train:
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

      # Predicated class is the one with the highest score
      preds = outputs.argmax(1)
      correct_mask = (preds == labels)

      # Overall totals (loss is weighted by batch size so the final mean is per image)
      total_loss += loss.item() * images.size(0)
      total_correct += correct_mask.sum().item()
      total_seen += images.size(0)

      # Years and periods present in this batch
      batch_years = torch.unique(years).tolist()
      batch_periods = torch.unique(periods).tolist()

      # Per class totals, further split by year and day/night
      for c in range(num_classes):
        class_mask = (labels == c)
        class_total[c] += class_mask.sum().item()
        class_correct[c] += (correct_mask & class_mask).sum().item()

        for y in batch_years:
          key = (c, y)
          cy_mask = class_mask & (years == y)
          class_year_total[key] = class_year_total.get(key, 0) + cy_mask.sum().item()
          class_year_correct[key] = class_year_correct.get(key, 0) + (correct_mask & cy_mask).sum().item()

        for p in batch_periods:
          key = (c, p)
          cp_mask = class_mask & (periods == p)
          class_period_total[key] = class_period_total.get(key, 0) + cp_mask.sum().item()
          class_period_correct[key] = class_period_correct.get(key, 0) + (correct_mask & cp_mask).sum().item()

      # Per year totals
      for y in batch_years:
        year_mask = (years == y)
        year_total[y] = year_total.get(y, 0) + year_mask.sum().item()
        year_correct[y] = year_correct.get(y, 0) + (correct_mask & year_mask).sum().item()

      # Per day/night totals
      for p in batch_periods:
        period_mask = (periods == p)
        period_total[p] = period_total.get(p, 0) + period_mask.sum().item()
        period_correct[p] = period_correct.get(p, 0) + (correct_mask & period_mask).sum().item()

  # Convert running totals into accuracies
  epoch_loss = total_loss / total_seen
  epoch_acc = total_correct / total_seen
  per_class_acc = (class_correct / class_total.clamp(min=1)).tolist()  # clamp avoids dividing by zero
  per_year_acc = {y: year_correct[y] / year_total[y] for y in year_total}
  per_class_year_acc = {
    c: {y: (class_year_correct[(c, y)] / class_year_total[(c, y)] if class_year_total[(c, y)] > 0 else None)
        for y in year_total}
      for c in range(num_classes)}

  per_period_acc = {p: period_correct[p] / period_total[p] for p in period_total}
  per_class_period_acc = {
    c: {p: (class_period_correct[(c, p)] / class_period_total[(c, p)] if class_period_total[(c, p)] > 0 else None)
        for p in period_total}
      for c in range(num_classes)
  }

  return epoch_loss, epoch_acc, per_class_acc, per_year_acc, per_class_year_acc, per_period_acc, per_class_period_acc

def evaluate_final(model, loader, idx_to_label, num_classes):
  '''
  Predict every image in `loader` and print a confusion matrix and a scikit-learn classification report
  (precision, recall, F1 per species).

  Returns:
    (confusion_matrix, classification_report_string)
  '''
  model.eval()
  all_preds, all_labels = [], []

  with torch.no_grad():
    for images, labels, years, periods in loader:
      images = images.to(device, non_blocking=True)
      outputs = model(images)
      preds = outputs.argmax(1).cpu()
      all_preds.extend(preds.tolist())
      all_labels.extend(labels.tolist())

  class_names = [idx_to_label[i] for i in range(num_classes)]

  cm = confusion_matrix(all_labels, all_preds, labels=list(range(num_classes)))
  print("\nConfusion matrix (rows = true species, columns = predicted species)")
  print("Order:", class_names)
  print(cm)

  report = classification_report(all_labels, all_preds, labels=list(range(num_classes)),
                                 target_names = class_names, digits=3, zero_division = 0)

  print("\nClassification report:")
  print(report)

  return cm, report

# --- Main ---

def main():
  '''
  Train the model, keep the best checkpoint, and run a final evaluation.
  '''
  print(f"seed = {seed}")
  print(f"Using {device} device")
  set_seed(seed)

  # --- Labels ---

  with open(label_map_json) as f:
    label_map = json.load(f)                           # species name -> class ID
  num_classes = len(label_map)
  idx_to_label = {v: k for k, v in label_map.items()}  # class ID -> species name (for readibility)
  print(f"Classes ({num_classes}): {list(label_map.keys())}")

  # --- Data loaders ---

  train_ds = CameraTrapDataset(train_csv, transform=train_transform)
  test_ds = CameraTrapDataset(test_csv, transform=test_transform)

  # Seeded generator so the training shuffle order is reproducible
  g = torch.Generator()
  g.manual_seed(seed)

  train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True, worker_init_fn=seed_worker, generator=g)
  test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True, worker_init_fn=seed_worker)

  # --- Model, loss and optimiser ---

  model = build_model(num_classes)
  criterion = nn.CrossEntropyLoss()
  trainable_params = [p for p in model.parameters() if p.requires_grad]  # only the final layer if frozen
  optimizer = torch.optim.Adam(trainable_params, lr=learning_rate)

  # --- Training loop ---

  period_names = {0: "night", 1: "day"}
  best_test_acc = 0.0

  for epoch in range(1, num_epochs + 1):
    # One training pass, then one evaluation pass on the test set
    train_loss, train_acc, _, _, _, _, _ = run_epoch(model, train_loader, criterion, num_classes, optimizer)
    test_loss, test_acc, test_per_class_acc, test_per_year_acc, test_per_class_year_acc, test_per_period_acc, test_per_class_period_acc = run_epoch(model, test_loader, criterion, num_classes, optimizer=None)

    print(f"\nEpoch {epoch:2d}/{num_epochs} | "
          f"train loss {train_loss:.4f} acc {train_acc:.3f} | "
          f"test loss {test_loss:.4f} acc {test_acc:.3f}")

    print("  Test accuracy by year:")
    for year in sorted(test_per_year_acc):
      print(f"    {year}: {test_per_year_acc[year]:.3f}")

    print("  Test accuracy by day/night:")
    for period in sorted(test_per_period_acc):
      print(f"    {period_names[period]}: {test_per_period_acc[period]:.3f}")

    # One line per species: overall accuracy, then by year, then by day/night
    print("  Per-class test accuracy (overall | by year | by day/night):")
    for class_idx, class_acc in enumerate(test_per_class_acc):
      species_name = idx_to_label[class_idx]
      year_accs = test_per_class_year_acc[class_idx]
      year_str = " | ".join(
        f"{year}: {year_accs[year]:.3f}" if year_accs[year] is not None else f"{year}: NA"
        for year in sorted(year_accs)
      )

      period_accs = test_per_class_period_acc[class_idx]
      period_str = " | ".join(
        f"{period_names[period]}: {period_accs[period]:.3f}" if period_accs[period] is not None else f"{period_names[period]}: NA"
        for period in sorted(period_accs)
      )

      print(f"    {species_name:25s} overall {class_acc:.3f} | {year_str} | {period_str}")

    # Save a checkpoint whenever the test accuracy improves
    if test_acc > best_test_acc:
      best_test_acc = test_acc
      torch.save({"model_state_dict": model.state_dict(), "label_map": label_map}, checkpoint_path)

  print(f"\nBest test accuracy: {best_test_acc:.3f}")
  print(f"Best checkpoint saved to {checkpoint_path}")

  # --- Final evaluation of the best checkpoint ---

  best_checkpoint = torch.load(checkpoint_path, map_location=device)
  model.load_state_dict(best_checkpoint["model_state_dict"])
  evaluate_final(model, test_loader, idx_to_label, num_classes)

if __name__ == "__main__":
  main()